### ISSUE TITLE
Assertion Failed

### ISSUE THREAD

**Issue by gristovski** [opencv/dldt#340] opened 2019-12-03 15:10 UTC
I am getting a cv2 assertion failed error on a model. The error message is as follows:
`cv2.error: OpenCV(4.1.2-openvino) /home/jenkins/workspace/OpenCV/OpenVINO/build/opencv/modules/dnn/src/op_inf_engine.cpp:704: error: (-215:Assertion failed) Failed to initialize Inference Engine backend: AssertionFailed: newDims[newPerm[i]] == 1 in function 'initPlugin'
`
I've tried the same network with variable input size to same results. Any ideas where could I look for the problem?

**Comment by alalek** [comment] 2019-12-03 15:49
> variable input size

duplicate of https://github.com/opencv/opencv/issues/15452

Consider providing minimal complete reproducer in comment of mentioned issue.

**Closed by alalek** 2019-12-03 15:49 UTC
